### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dmamontov** [brunonova/nautilus-admin#49]
Nautilus-Python-WARNING **: 00:27:38.384: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-admin.py", line 20, in <module>
    from gi import require_version
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError

**Comment by dmamontov** [comment]
Updated python and everything is ok.
